### ISSUE TITLE
Webcat (and Webpirate) taking ages to start

### ISSUE THREAD

**Issue by popanz** [llelectronics/webcat#84] opened 2020-08-19 14:56 UTC
I reflashed my pro1, now Webcat start is really really slow.

When I start from cli I get this:
unknown:0 - const QList<TransferMethodInfo>& TransferEngine::transferMethods() "Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken."
Webcat starts after after 30 seconds and I can use it then without bigger issues. 

I think it is something QTWebkit related, but I don't know, where to look for, a solution.

**Comment by llelectronics** [comment] 2020-08-19 23:30
Nothing QtWebkit related. 
The Share menu loading does not reply anything for you. So your share menu is broken apparently. Check if you have some addons installed that are incompatible with it. 

I have to close this as it is not a bug in webcat

**Closed** 2020-08-19 23:31 UTC
Labels: invalid

**Comment by popanz** [comment] 2020-08-20 07:39
Thanx, your answer helped me to find the solution. The culprit was the owncloud sharing plugin.
